### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#183]
v 1.0
- [x] Home page with upcoming event 
- [x] Authorization (register / login / password change)
- [x] Event attend
- [x] Visit confirmation
- [x] Emails
- [x] Test

v 1.1
- [ ] Talks#index
- [ ] Talks#show
- [ ] Filter talks by tags
- [ ] Manage profile

v. 1.2
- [ ] Events#index
- [ ] Events#show
- [ ] Search events and talks
- [ ] Decomposition talks.tags to event

v 1.3
- [ ] Potential talk topics voting
- [ ] Members#index
- [ ] Members#show
- [ ] Search +members

**Comment by kushniryb** [comment]
@sveredyuk What's up with the search module?

**Comment by sveredyuk** [comment]
Moved to page: https://github.com/pivorakmeetup/pivorak-web-app/wiki/Roadmap
