### ISSUE TITLE
BooksBunker

### ISSUE THREAD

**Issue by sveredyuk** [pivorakmeetup/pivorak-web-app#527]
**Idea:** Create closed (access limited) club for books reader (maybe not only technical).
**First rule of bunker:** You know it very well :)
**How to get in:** Share one of your e-book that' yet is not in bunker's collection or buys and share one of the recommended books (list be available at the bunker's entrance)
**Inside:** All bunker's members have access to download any book and share new books.
**Terms of use**: Don't share this books outside the bunker. All books must be legal. Only bought books could be shared in the bunker.

**Technical side:**
`https://pivorak.com/bb` - WIP as engine.

**TODO:**
- [x] 0. Bootstarb new BB component
- [ ] 1. You make "knock" and share the book.
- [ ] 2. Bunker's admin decides to enter you or not.
- [ ] 3. Inside bunker, you can add new books
- [ ] 4. All books should be moderated.
- [ ] 5. You can download any book.
- [ ] 6. Bunker track all downloads and show some sort of statistic.
- [ ] 7. Everyones happy

@denysmedynskyi @floor114 FYI

**Comment by sveredyuk** [comment]
Redundant
